[project]
name = "break-down"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=0.1.0",
    "mcp>=1.6.0",
    "anthropic>=0.27.0",
]

[tool.uv]
